name: Nightly Build android

on:

  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/android-only.yml 
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
